# 工作流名称
name: build and deploy
# 触发条件
on:
  # 推送到 main 分支时自动部署
  push:
    branches: ["main"]
  # 手动部署
  workflow_dispatch:
# 任务列表
jobs:
  # 任务 id
  deploy:
    # 运行环境：ubuntu 最新版本
    runs-on: ubuntu-latest
    # 所需权限
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    # 步骤
    steps:
      # 检出源代码
      - name: Checkout sourc code
        uses: actions/checkout@v3
      # 安装 npm yarn 依赖等
      - name: NPM install
        uses: bahmutov/npm-install@HEAD
        with:
          install-command: yarn
      # 构建
      - name: Build dist
        run: yarn run build
      # 把 dist 目录推到 gh-pages 分支
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
         publish_dir: ./dist
